export const ROOMS_ISDIFFICULT_KEY= import.meta.env.VITE_API_KEY_ROOMS_ISDIFFICULT;
export const INVITE_ID_KEY= import.meta.env.VITE_API_KEY_ROOMS_ID;
export const ROOMS_ISSUCCESSFUL_KEY= import.meta.env.VITE_API_KEY_ROOMS_ISSUCCESSFUL;
export const HOST_NAME_KEY= import.meta.env.VITE_API_KEY_ROOMS_STATUS_HOST_MEMBER;
export const GUEST_NAME_KEY= import.meta.env.VITE_API_KEY_ROOMS_STATUS_GUEST_MEMBER;