name: main
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: main
        uses: appleboy/ssh-action@master
        uses: volta-cli/action@4
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          proxy_host: ${{ secrets.PROXY_HOST }}
          proxy_username: ${{ secrets.USERNAME }}
          proxy_password: ${{ secrets.PROXY_PASSWORD }}
          node-version: 16.x
          npm-version: 8.19.4
          run: cd /var/www/procon34_CYBER_WARS_frontend/
          run: git pull origin main
          run: npm install